### ISSUE TITLE
New Guidecurves

### ISSUE THREAD

**Issue by GoogleCodeExporter** [DLR-LY/CPACS#379]
```
The steadiness information C1, C2, C3 will become obsolete in CPACS 2.2.1 as we 
are introducing guidelines to the geometry definition. Therefore, it will be 
deleted here, before anyone starts to develop around this feature.
```

Original issue reported on code.google.com by `daniel.b...@googlemail.com` on 26 Feb 2014 at 8:58

**Comment by DLR-boeh-da** [comment]
Guidecurves will go live into CPACS 2.3. An updated may be included in CPACS 2.3.1

**Comment by DLR-LY** [comment]
The guide curves are beeing implemented and tested in the TIGL library.
The CPACS definition will be adapted once the implementation tests are finished.

**Comment by yohanzuo** [comment]
Is there any documentation about guide curves?Does it has the same definition and function as Loft guides in Catia ?For the guide curve, what is the related openCASCADE api used in TIGL library?

**Comment by DLR-LY** [comment]
Together with the TIGL developers we are still working on the guide curves. I don't know how the loft guides are defined in Catia. For questions on implementation details consider posting an issue for the TIGL developers at https://github.com/DLR-SC/tigl.

**Comment by codingpoets** [comment]
The discussion on guide curves is continued in #458
