### ISSUE TITLE
Definition of String Vector

### ISSUE THREAD

**Issue by GoogleCodeExporter** [DLR-LY/CPACS#408]
```
Added a new definition for a string vector type in CPACS 2.2.1

Need to fix the format for this type and update CPACS 2.2.1
```

Original issue reported on code.google.com by `daniel.b...@googlemail.com` on 27 Mar 2015 at 9:22

**Comment by DLR-boeh-da** [comment]
This also needs to include the extension toward a stringUIDBaseVectorType --> updated parentUID node in the massBreakdown

**Comment by codingpoets** [comment]
stringUIDBaseVectorType does not exist. Since the issue is very old and I don't fully understand it I will close it. In case somebody objects, please leave a comment.
