### ISSUE TITLE
AeroPerformanceMap altitude as an option and angle naming

### ISSUE THREAD

**Issue by boeh-da** [DLR-LY/CPACS#422]
AS proposes to have altitude as an alternative parameter opposed to Re. 

pros:
- Most of the time altitude is the parameter one is looking for
- Similar setup as the engine performance map

cons: 
- Several tools would need adjustment
- Depending on the implemented solution this may become optional, and hence, demand more implementation effort

**Comment by DLR-boeh-da** [comment]
Additionally, angle of yaw is probably the wrong name, we are looking for angle of sideslip

**Comment by codingpoets** [comment]
Closed with #518
