### ISSUE TITLE
CPACS-Initiator

### ISSUE THREAD

**Issue by danieldevries6** [DLR-LY/CPACS#426]
For the Initiator input we need the following tool specific input structure:
Under: cpacs/toolspecific/initiator:
* settings:
 * NumberOfFlights
 * AirworthinessRegulations (a string e.g. 'FAR-25')
 * LoiterTime
 * DivRange
 * WingLocation (a string e.g. 'High', 'Mid', 'Low')
 * TailType (a string e.g. 'Standard', 'T-tail')
 * RootAirfoil (string which refers to the names of airfoils available in the Initaitor database)
 * KindAirfoil (")
 * TipAirfoil (")
 * Parts (elements like 'Fuselage' or 'Wing' with a type attribute)
* initialguesses:
 * LDmax
 * SFC
 * FFStartUp
 * FFTaxi
 * CLmaxLanding
 * CLmaxTakeOff
 * CLmaxClean
 * WingAspectRatio

Some notes: The initialguesses are values that the Initiator needs as initial guesses. These values, like the settings, will not be changed by the Initiator. But the acutal results of the DesignConvergence of the Initiator will be put into the right areas of CPACS. So as a general note about these: don't use them to do further calculations with! These are only inputs for the Initiator. Not outputs.

Output:
The initiator calculates the SFC of the Engines. These could be put into CPACS. The proposed location to store this data is the following path:
/cpacs/vehicles/engines/engine/analysis/sfc00

**Comment by DLR-LY** [comment]
As mentioned in the telco last year, there is no need to add toolspecific definitions in CPACS. You can just add the xml-nodes in your CPACS files. The toolspecifics can simply be used without explicit definition in CPACS.
