### ISSUE TITLE
TU Delft EMWET tool specific inputs

### ISSUE THREAD

**Issue by RobinAugy** [DLR-LY/CPACS#427]
Dear reader,

I am currently implementing CPACS into the TU Delft tool EMWET. I have a few inputs that I need that currently do not have a spot in CPACS. These could possibly be added into CPACS itself at some point, but at this moment it would be fine to have these as tool specific inputs. Thus I would request that in cpacs/toolspecific a folder EMWET would be created. In this folder, I would like to request the fields:

cpacs/toolspecific/EMWET/wingUID (type: string)
cpacs/toolspecific/EMWET/loadcaseUID (type: string)
cpacs/toolspecific/EMWET/fueltank/y_start (type: float)
cpacs/toolspecific/EMWET/fueltank/y_end (type: float)
cpacs/toolspecific/EMWET/stringerefficiency (type: float)

If you have any questions, you can contact me about them. In addition, tomorrow (20-11) during the AGILE telco Imco will discuss the issues reported for TU Delft tools EMWET, Q3D and the Initiator. Thus, he will be able to elaborate on this request.

Thank you for your time!

**Comment by DLR-LY** [comment]
Dear Robin,
As discussed in the telco with Imco there is no need to explicitly define the toolspecifics in CPACS. Just use them in your CPACS files.
