### ISSUE TITLE
Question, nacelle geometry

### ISSUE THREAD

**Issue by aa-savelyev** [DLR-LY/CPACS#429]
Hi all!
I have a question about CPACS Documentation.
If I understand properly, it should be a scheme of nacelle. But I can't find any.
![capture](https://cloud.githubusercontent.com/assets/8608007/11282735/f2280206-8f11-11e5-9e89-1fc6a0449ee2.PNG)

**Comment by DLR-LY** [comment]
Hi,
thank you for reporting the bug. Will be fixed in the next release.

**Comment by DLR-LY** [comment]
Fixed in CPACS 2.3.1 release.
