### ISSUE TITLE
Sweep Angle

### ISSUE THREAD

**Issue by Luque9** [DLR-LY/CPACS#430]
I'm Luca Stingo, University of Naples Federico II (UNINA) student.
In the CPACS file 'D150_AGILE.xml' the tag < sweepAngle > about vertical tail (Seitenleitwerk) : 
< positioning uID="D150_VAMP_SL1_Pos2" xsi:type="positioningType" >
                                < name >Seitenleitwerk_Position2< /name >
                                < sweepAngle >40.3982< /sweepAngle >
                            < fromSectionUID >D150_VAMP_SL1_Sec1< /fromSectionUID >
                                < toSectionUID >D150_VAMP_SL1_Sec2< /toSectionUID >
                            < /positioning >
But using CAD software Vertical tail sweepangle value is 42,598°;to what corresponde the value 40.3982?

In the CPACS file 'D150_AGILE.xml' the tag < sweepAngle > about wing  : 
< positioning uID="D150_VAMP_W1_Pos3" xsi:type="positioningType" >
                                < name >Wing_Position3< /name >
                                < sweepAngle >27.3288085125< /sweepAngle >
                            < fromSectionUID >D150_VAMP_W1_Sec2< /fromSectionUID >
                                < toSectionUID >D150_VAMP_W1_Sec3< /toSectionUID >
                            < /positioning >
But using CAD software Vertical tail sweepangle value is 27,748°;to what corresponde the value 27.328?

About Horizontal tail this incongruity doesn't exist.

These value are very important to estabilish wing and vertical tail dimensions for some tools.

Thanks

**Comment by DLR-LY** [comment]
Hi Luca,

The positioning node adds a translation to the toSection.
The sweep angle can only be directly retrieved from the positioning if there is no other transformation affecting the section in the CPACS file. Retrieving the leading edge sweep for a shape requires you to calculate it from the leading edge positions of the two elements considering the transformations on all the levels (component level, section level, positionings, element level and the profile definition).
If in the profile definition the leading edge point is not at the origin, the calculation could be more difficult. In general I would suggest to use the TIGL library. TIGL takes care of all the transformations and can be used to access e.g. surface or chord points.
