### ISSUE TITLE
Revise the definition of component segments

### ISSUE THREAD

**Issue by DLR-LY** [DLR-LY/CPACS#431]
The ComponentSegments in CPACS are ill defined. A mathematical well defined ComponentSegment needs to be developed. This change has an effect on all the nodes relying on the ComponentSegment eta xsi coordinate systems such as wing structure and control surfaces.

**Comment by codingpoets** [comment]
New definition introduced and documented in 8bef2abd291ddf37dcbc418120908eaed19f7ecf.
Thus closing this issue.
