### ISSUE TITLE
Definition of Control Laws

### ISSUE THREAD

**Issue by DLR-LY** [DLR-LY/CPACS#434]
For the AGILE project we need a definition of control laws in CPACS.
This node is essential for less-/unconventional configurations such as boxwing design, BWB or UAVs.
Something like fractions for each control device could be defined with respect to the three functions pitch, yaw and roll.

**Comment by DLR-LY** [comment]
There already is a definition of controlLaws in CPACS at
/cpacs/vehcicles/aircraft/model/systems/controlLaws.
It needs to be checked whether this node already satisfies all the requirements.

**Comment by codingpoets** [comment]
It seems not to have been a problem within the project.
No changes required.
