### ISSUE TITLE
Add thermal material properties

### ISSUE THREAD

**Issue by rainman110** [DLR-LY/CPACS#435]
In an internal DLR project, we want to compute radar and infrared signatures from aircraft. To do so, we need to add some basic thermal properties of materials, which are:

 - Thermal conductivity
 - Specific heat
 - Diffuse emissivity

These should be added to 

    /cpacs/vehicles/materials/material/

As the diffuse emissivity depends on the spectral wave length it should be stored as an array including wave length and the emmisivity factor.

The specific heat typically depends on the temperature. Therefore, it also needs to be an array including temperature and value.

**Comment by rainman110** [comment]
What unit if measurement should we use for the wavelength? Internally, micrometers are normally used but that might conflict with the SI unit system that is used in CPACS elsewhere.

@DLR-LY what do you think?

**Comment by DLR-LY** [comment]
I agree that we should consistantly use SI units throughout CPACS. Any exceptions would lead to uncertanties in the interpretation. I'd suggest we keep it clean by sticking to SI units for all values.

**Comment by DLR-LY** [comment]
Merged into main development branch. Will be available at the next release 2.3.1 at the end of this month.

**Comment by rainman110** [comment]
Perfect, thanks! :smile:
