### ISSUE TITLE
Aircraft model reference type

### ISSUE THREAD

**Issue by sdeinert** [DLR-LY/CPACS#446]
Currently the CPACS schema expects all child elements of the reference node to be present, if reference is defined. Should it be possible to define, for example, only the reference area without having to specify a reference point?
In other words could the elements area, length and point be changed to optional in the schema?

**Comment by DLR-LY** [comment]
From a user perspective I do agree that there might be cases where you do not want to give all the reference values. I think this could be changed in the next version.
Does anyone object?

**Comment by CLiersch** [comment]
I do not like the idea so much of having an incomplete reference node. Of course, if you e.g. just have an aero Performance map containing cfx and cfz you might not need a Moment reference point. On the other Hand, aero tools tend to self-specify undefined reference values and so there is some danger of getting cofficients based on not explicitely specified references into the dataset. Certainly, this danger is quite vague but it is also not much effort to create a complete reference node. So, my oppinion here is based more on personal taste than on real advantages and disadvantages of one of the solutions

**Comment by DLR-LY** [comment]
I think as long as there is no data which requires for instance the reference length the user should not be forced to set a value for it. In case tools like aerodynamic analysis tools which need the value to write their results to CPACS but cannot find a value for it in the reference node, should be allowed to make an assumption but then be forced to write that value into CPACS. Thus in my opinion the convention should be that any user or tool who/which creates data based on a parameter not yet specified in CPACS needs to write the assumption to the appropriate node.

**Comment by codingpoets** [comment]
Closed by d70c57bf7ce568f6b92109c35a4c59b057b6de54
