### ISSUE TITLE
Nonlinear wing tapper and sweep

### ISSUE THREAD

**Issue by yohanzuo** [DLR-LY/CPACS#447]
How to define a wing with nonlinear tapper and sweep(Now I can only deal with piecewise linear sweep wing with CPACS)？Is this related to the guidecurve of the wing node?

**Comment by DLR-LY** [comment]
The geometry definition based on segments is defined to have a linear connection between two profiles/elements. Indeed the guide curves are introduced to allow segments to have a non linear shape and to allow a smooth connection of two adjacent segments by giving continuity constraints.
But the definition of the guide curves is still in a development state and could be changed in the next release. Once the final definition has been tested with a reference implementation in the TIGL library it will be released.

**Comment by codingpoets** [comment]
Topic discussed in #458 (although not actively)
