### ISSUE TITLE
Should we set all uID attributes to use="required"?

### ISSUE THREAD

**Issue by sdeinert** [DLR-LY/CPACS#450]
For example in the wing componentSegment branch, the definition of the uID attribute is not consistent. Sometimes the attribute uID is set to required sometimes optional.
As uIDs are used for referencing throughout the CPACS structure, shouldn't it be mandatory to define a uID for all elements that can be referenced?

The current state requires going back and forth between the defined elements always setting the uID once a reference to this element is required, since one probably forgets setting it when creating the element. Currently it requires the user to have in mind all the elements that might have an uID attribute in order to distinguish those from the elements that do not have an uID attribute.

In my opinion it would be much more straight forward when creating a new CPACS file based on the schema that all uID attributes are required and have to be filled in during creation of the respective element.

**Comment by DLR-LY** [comment]
Thank you for that comment. I totally agree.
All the uID attributes should be mandatory. I appointed this task to the next release. I guess it should be straight forward to change that.

**Comment by DLR-BT** [comment]
DLR-BT agrees to finally set all uID definitions to required. This may cause some uID atrtributes in the schema to be deleted, when they are not really required
