### ISSUE TITLE
Using a spar uid as ribRotationReference is not possible any more since the type changed to an Enumeration

### ISSUE THREAD

**Issue by RlanderRISCSW** [DLR-LY/CPACS#456]
In CPACS 2.2 it was possible to define a spar as ribRotationReference via its UID, since the type was defined as stringBaseType.
Since CPACS 2.3 the stringBaseType was restricted to predefined enumeration values. For spars two enumeration values "FrontSpar" and "RearSpar" were added, but it is not possible to reference spars via their UID any more. This limits the way ribs can be specified, is there a reason for this limitation? For our purposes we would prefer to be able to use UIDs again.

**Comment by codingpoets** [comment]
This was introduced due to issues described in #290. Do you think that the issue described there does not arise when using spar UIDs?

**Comment by rmaierl** [comment]
I think this Issue can be included into #544

**Comment by RlanderRISCSW** [comment]
It's not clear to me how this change is related to #290. From my understanding #290 was a question how to apply the rotations correctly in a twisted wing.
The change from the definition of the ribRotationReference from CPACS 2.2 to CPACS 2.3 did not change anything in the way how the rib is defined. It is still possible to define the leading edge, trailing edge, or a spar as the ribRotationReference. The only change was that instead of allowing to use a string for the definition of the ribRotationReference, which was either "Leading Edge", "Trailing Edge" or a sparUID, now an enumeration is used. This enumeration still contains Leading Edge, Trailing Edge, but does not allow to define a specific sparUID any more. Instead the enumeration provides two values "FrontSpar" and "RearSpar", which limit the number of spars the user can use as reference (not taking into account that the geometry would have to be analyzed in order to identify the front and rear spar)

**Comment by codingpoets** [comment]
Thanks for confirming. To be honest I wasn't sure whether #290 was relevant for this issue. But since you confirm that it is not I don't see a reason not to switch back from enum to string for the _ribRotationReference_ in _ribRotationType_.
