### ISSUE TITLE
Proposal: Simplified Guide Curve Definition

### ISSUE THREAD

**Issue by rainman110** [DLR-LY/CPACS#458]
As discussed at the CPACS Developer Meeting at 11/22/2016, there is a concept for a simplified guide curve definition.

The proposal is the following (see next comment)

 - Define anchor points on both sections that should be connected
 - The ry-coordinate defines a point on this line by linear interpolation
 - The x-direction is a user defined direction which is global for the whole curve. The rx coordinate defines a point along this direction.
 - The z-direction is the cross-product Xdir x Ydir.

Pros:
 - Guide curve geometry is independent from the profiles
 - Unique transformation from spacial coordinates to guide curve coordinates (really?)
 - More user-friendly way to define guide curves

Cons:
 - Preferential direction is global to the curve -> there are (pathological?) curves that can not be parameterized

What are the general feelings and concerns about it?

Things to be done for a further discussion
- [ ] Make a CPACS schema proposal
- [ ] Find use-cases, in which the simplified proposal makes problems
- [ ] Vote for either the old or the new definition. Collect votes from the most important disciplines and people.
- [ ] Integration in CPACS 3.0?

To be further discussed...

**Comment by rainman110** [comment]
Scheme for new definition:

![newguidecurves](https://cloud.githubusercontent.com/assets/3213107/20527825/20d081a2-b0ca-11e6-8211-4fc89ddb0268.png)

**Comment by DLR-Wunder** [comment]
The current guide curve definition and the simplified guide curve definition has been implemented and tested in combination with CATIA V5.

For the modeling of an conventional aircraft configuration (Common Research Model) the simplified guide curve definition works fine and is more robust in comparison to the current definition.
Furthermore, the simplified guide curve definition is more intuitive for an aircraft designer.

So I vote for the simplified guide curve definition and the integration in CPACS Version 3.0, which only makes sense in combination with the corresponding TIGL support.

**Comment by rainman110** [comment]
@DLR-Wunder and @codingpoets What is the current status with the guide curve definition? Is a decision already been made?

**Comment by DLR-Wunder** [comment]
For conventional aircraft configuration the simplified guide curve definition works fine. I see no problems in my applications so far. So I vote for the simplified guide curve definition. But the decision process is not clear for me.

**Comment by codingpoets** [comment]
In comparison with the previous/current definition, what is there to be changed? Is it only a different interpretation of the same data? In that case, who can provide an anambiguous description of the definition?

**Comment by DLR-Wunder** [comment]
Hallo Jonas,

im Anhang findest Du die Dokumente, welche die vereinfachte Definition der Führungskurven beschreiben.
Diese beinhalten auch die entsprechenden Skizzen (nicht besonders schön, aber selten).

Im CPACS-Schema sind keine Unterschiede zwischen der „aktuellen“ und der „vereinfachten“ Beschreibung der Führungskurven.
In beiden Fällen werden die Bezeichnungen „rX“, „rY“ und „rZ“ verwendet.
Der Unterschied liegt in der Interpretation.
Dabei ist darauf hinzuweisen, daß sich bei der Beschreibung einer Führungskurve die Daten der „aktuellen“ und der „vereinfachten“ Beschreibung unterscheiden!
Bei der vereinfachten Definition der Führungskurven haben wir uns darauf verständigt, daß die globale x-Richtung auch vom Anwender vorgebbar sein sollte.
Dies ist im Schema noch zu ergänzen.

Bei weiteren Fragen melde Dich einfach nochmal bei mir.

Viele Grüße,
Tobias


——————————————————————————
Deutsches Zentrum für Luft- und Raumfahrt e.V. (DLR)
Institut für Aerodynamik und Strömungstechnik | Transportflugzeuge | Lilienthalplatz 7 | 38108 Braunschweig

Dr.-Ing. Tobias Wunderlich
Telefon 0531 295-2816 | Telefax 0531 295-2320 | tobias.wunderlich@dlr.de<mailto:tobias.wunderlich@dlr.de>
DLR.de<http://www.dlr.de/>

Von: Jonas Jepsen [mailto:notifications@github.com]
Gesendet: Montag, 18. Dezember 2017 11:08
An: DLR-LY/CPACS
Cc: Wunderlich, Tobias; Mention
Betreff: Re: [DLR-LY/CPACS] Proposal: Simplified Guide Curve Definition (#458)


In comparison with the previous/current definition, what is there to be changed? Is it only a different interpretation of the same data? In that case, who can provide an anambiguous description of the definition?

**Comment by rainman110** [comment]
The global x direction is already in the schema. This was merged yesterday as part of a pull request.

**Comment by codingpoets** [comment]
@DLR-Wunder could you digitize the illustrations and translate the terms into english?

**Comment by DLR-Wunder** [comment]
Hallo Jonas,

komme in nächster Zeit nicht dazu neue Skizzen anzufertigen.

Viele Grüße,
Tobias


——————————————————————————
Deutsches Zentrum für Luft- und Raumfahrt e.V. (DLR)
Institut für Aerodynamik und Strömungstechnik | Transportflugzeuge | Lilienthalplatz 7 | 38108 Braunschweig

Dr.-Ing. Tobias Wunderlich
Telefon 0531 295-2816 | Telefax 0531 295-2320 | tobias.wunderlich@dlr.de<mailto:tobias.wunderlich@dlr.de>
DLR.de<http://www.dlr.de/>

Von: Jonas Jepsen [mailto:notifications@github.com]
Gesendet: Dienstag, 19. Dezember 2017 14:39
An: DLR-LY/CPACS
Cc: Wunderlich, Tobias; Mention
Betreff: Re: [DLR-LY/CPACS] Proposal: Simplified Guide Curve Definition (#458)


@DLR-Wunder<https://github.com/dlr-wunder> could you digitize the illustrations and translate the terms into english?

**Comment by codingpoets** [comment]
Continued in #526
