### ISSUE TITLE
rearrange items in mComponentSegment

### ISSUE THREAD

**Issue by sfreund-DLR** [DLR-LY/CPACS#460]
referring to this element: cpacs/vehicles/aircraft/model/analyses/massBreakdown/mOEM/mEM/mStructure/mWingsStructure/mWingStructure/mComponentSegments/mComponentSegment 

It contains a **mWingBox** which seems to define all structure masses that compose the wing box. Thus **mFixedLeadingEdge** and **mFixedTrailingEdge** is included in this. Those two, should probably be placed on level up.

**mFixedLeadingEdge** and **mFixedTrailingEdge** also have only on element. It should be an iterable in order to define several masses of the same kind. This also applies to /mSkins/mLowerShell and /mSkins/mUpperShell.

**Comment by rmaierl** [comment]
Thank you for bringing up this topic. I also think, that the definitions in this branch need some attention.

I ignored **mFixedLeadingEdge** and **mFixedTrailingEdge** in my implementation and used only the **mSkins** branch to save the results for the wing skin of my mass calculation.

To satisfy my needs I added the node for **mCells** in _.../mWingBox/mSkins/mLowerShell_ and _.../mUpperShell_. This is also shown in the attached figure.

The structure of the **mComponentSegment**  branch is build up from mass report structures, but it is difficult to find out which structural elements from the **componentSegment**
 are part of the wing box, and which not. 

![massmodelstructure](https://cloud.githubusercontent.com/assets/10923333/21106314/f2b354c4-c08d-11e6-9363-be1e36b90ed0.png)

**Comment by sfreund-DLR** [comment]
Thanks for the quick reply!

So for the next CPACS release, we should make mSkin(s) and mStringers iterable in oder to make them satisfy your way to write the masses?
best regards

**Comment by rmaierl** [comment]
The _mSkin_ node is from type massDescription (which is still CPACS 2.2) and contains all parts of the shell, which are not defined in a Cell.

I think a good solution for my needs would be:

 - mLowerShell [1]
 -- massDescription [1] (type massDescription -> sum of all shell)
 -- mSkin [1] (type massDescription)
 -- mCells [0,1] (container)
 --- massDescription [1] (type massDescription -> sum of all cells)
 --- mCell [1,*] (type massDescription)
 -- mStringers [0,1] (container)
 --- massDescription [1] (type massDescription -> sum of all stringer)
 --- mStringer[1,*] (type massDescription)

Furthermore I added a node _secondaryMass_ to the massDescription type to model secondary (non carrying) structural mass.

**Comment by codingpoets** [comment]
It really looks like there is a need for extending the massBreakdown structure to the single stringer level.
For consistency with the definition in CPACS 2.3 I suggest we keep an additional massDescription in every element. That means that instead of making the mStringer nodes of type massDescription we should add a massDescription element to each of the leaves. That allows us to keep the same structure on every level of the massBreakdown.

Considering also other discussions it seems that there is an agreement that the **mFixedLeadingEdge** and **mFixedTrailingEdge** should be moved to the next higher level (mComponentSegment).

**Comment by codingpoets** [comment]
I revised the structure of the mComponentSegment node and its sub nodes.
Please check the [wingMasses](https://github.com/DLR-LY/CPACS/tree/wingMasses) branch to see the changes.

**Comment by sfreund-DLR** [comment]
Thanks for the extension!

The mShellType is a bit confusing to me. I guess, the **mCells** is redundant to **mSkins** and **mStringers**. Thus I would recommend to remove **mCells**.

The other modifications seem consistent to me.

**Comment by rmaierl** [comment]
I did not find a mCell node in this branch...

The masses of each cell and stringer (per skin / per cell / explicit) are necessary for my CSM generation to apply the secondary structural mass.

If the CPACS mass branch will change like this I have to keep the current definition to maintain my capabilities.

**Comment by DLR-LY** [comment]
Did you check in the right node? The mCells node is a child node of the mShellType.
![grafik](https://user-images.githubusercontent.com/16148180/27074715-3a22ae2a-5028-11e7-9e12-9b5dd7886a71.png)

**Comment by rmaierl** [comment]
I opened _schema/cpacs_schema.xml_ of the wingMasses branch and did not find a node called mCell in there.

**Comment by DLR-LY** [comment]
Please double check. See mCellsType.
![grafik](https://user-images.githubusercontent.com/16148180/27084294-9d8199b8-504b-11e7-9452-37d5bb7d6587.png)

**Comment by codingpoets** [comment]
By the way you don't have to check the schema file but can also check the documentation file which is build with every commit. Just click the green symbol in the branch view

![grafik](https://user-images.githubusercontent.com/10432668/27084545-931deb92-504c-11e7-91cc-2c0900d63104.png)

and click on the link to artifacts

![grafik](https://user-images.githubusercontent.com/10432668/27084596-c2cb6b76-504c-11e7-872c-f11e89da9837.png)

Then you should see the link to for downloading the documentation file.

![grafik](https://user-images.githubusercontent.com/10432668/27084644-eae95ac8-504c-11e7-98e8-6ca5b038077f.png)

**Comment by rmaierl** [comment]
Well hidden, the documentation.
But I found it...and the cell.
