### ISSUE TITLE
transformationType should use xsd:all instead of xsd:sequence

### ISSUE THREAD

**Issue by ArneBachmann** [DLR-LY/CPACS#472]
The order of application in a transformation is defined in the CPACS documentation (scale, rotate, translate), therefore we might use xsd:all instead of xsd:sequence, and remove all `occurs` alltogether.

**Comment by ArneBachmann** [comment]
Also applies for pointAbsRelType, pointType

**Comment by CLiersch** [comment]
You are absolutely right that an "xsd:all" is sufficient here and we should prefer "all" where possible. The idea, why we once made this a "sequence" was to avoid a chance of misinterpretation here. Even though the transformation order is mentioned in the documentation (nowadays), one could assume that writing e.g. "translation" first could lead to really doing the Translation before the other Transformation. Using the sequence, it is always assured that the three transformations are Standing in the order in which TiGL applies them. So I would rather suggest to keep it as a sequence here.

For the Points, I think a sequence is really not required, but the idea was here that the Points were used for the tranformation/Rotation node as well and there the order again becomes important.

**Comment by codingpoets** [comment]
Experience shows that in practice the order of translation, rotation and scaling is arbitrarily written in CPACS files. This is one of the things spamming the results when performing a validation of CPACS files against the schema.
Therefore I would rather change the type to xsd:all as suggested by @ArneBachmann.
If we continue to enforce the order, there should at least be a tixi function which reorders the nodes in the right sequence or supports you in writing it in the correct order.

**Comment by codingpoets** [comment]
Closed with #520
