### ISSUE TITLE
controlSurfaceSkinCutOutBorderType is a choice with only one option

### ISSUE THREAD

**Issue by ArneBachmann** [DLR-LY/CPACS#474]
The only offered choice option is a sequence of choice of sequences.
The outermost choice is definitely not required.

**Comment by ArneBachmann** [comment]
`cellPositioningSpanwiseType` does it correctly.

**Comment by rmaierl** [comment]
I agree, this node was intended  with the same functionality as a span-wise cell border in a different environment.

And I think you would like to say:
_The outermost **Sequence** is definitely not required._

**Comment by codingpoets** [comment]
> The outermost Sequence is definitely not required.

I agree.
