### ISSUE TITLE
pistonType uses xsd:sequence instead of xsd:all

### ISSUE THREAD

**Issue by ArneBachmann** [DLR-LY/CPACS#476]
Because it extends `strutType` which does it.
But in `strutType` we could move to `xsd:all` instead and change the `minOccurs` accordingly, to remove the constraint of the element order.

**Comment by ArneBachmann** [comment]
Unless type extension always introduces an implicit sequence, that is.

**Comment by codingpoets** [comment]
Indeed there seems to be an issue with the type extension, which always implies a sequence.
A similar issue, on extending a choice, is discussed here:
http://stackoverflow.com/questions/9008622/how-to-extend-a-choice-complextype-without-sequencing-the-choice

On the one hand the "group" element might be a simple way to avoid this issue. It would serve as an alternative to the the inheritance mechanism for reusing a specific definition.

**Comment by codingpoets** [comment]
It seems there is no simple way to fix this and since it is nothing serious I am closing this issue. Feel free to reopen if you feel this still should be adressed.
