### ISSUE TITLE
Anonymous element definition for fuselagePanelings empty in vSAeroSurfacePanelingsType

### ISSUE THREAD

**Issue by ArneBachmann** [DLR-LY/CPACS#479]
Anonymous element definition for `fuselagePanelings` empty in `vSAeroSurfacePanelingsType`.
It only reads
```
<xsd:element minOccurs="0" name="fuselagePanelings">
	<xsd:annotation>
		<xsd:documentation>Paneling for each fuselage</xsd:documentation>
	</xsd:annotation>
</xsd:element>
```

**Comment by CLiersch** [comment]
This is a placeholder for future development of the CPACS4VSA Interface (Extension to model the aircraft model including fuselages)

**Comment by ArneBachmann** [comment]
Well, this non-element broke my CPACS converter, I had to put it on a "no-fly" list :-)
However I wonder if it is wise to put unfinished definitions in the official standard instead of first completing  their definition, at least partially, e.g. on a branch.
