### ISSUE TITLE
Typo in guideCurve element

### ISSUE THREAD

**Issue by codingpoets** [DLR-LY/CPACS#489]
Description of fromGuideCurveUID should be:
Reference to the **previous** guide curve from which this guide curve shall start.

**Comment by morrme** [comment]
hi! i can't seem to find the file that this is in.

**Comment by ArneBachmann** [comment]
It's right there: https://github.com/DLR-LY/CPACS/blob/master/schema/cpacs_schema.xsd

**Comment by morrme** [comment]
@ArneBachmann thanks! I created a PR with the fix.
