### ISSUE TITLE
Having trouble designing fuselage in CPACS

### ISSUE THREAD

**Issue by vaggos322** [DLR-LY/CPACS#491]
Hello!
I am having trouble to design a fuselage in CPACS. I need it for my thesis which is based on CPACS. The wing was designed like a charm but I am having troubles to figure out how to design the fuselage because I tried to do it with the same principle as the wing and I did not get results at all. Any tips or even better a guide would be great. Thanks a lot.
Evangelos

**Comment by codingpoets** [comment]
Dear Evangelos,
Could you tell a bit more about the specific problem you have in creating a fuselage?
It really is very similar to the wing shape. I have created and attached a very simple example on how to define a fuselage segment in CPACS.
 
[simple_fuselage.zip](https://github.com/DLR-LY/CPACS/files/945690/simple_fuselage.zip)

You can use the example file as a starting point to transform the shape and adding more segments.

Jonas

**Comment by vaggos322** [comment]
Hello Jonas!

Thanks for your answer. The problem is ,when I put the profile uid's for the fuselage in the fuselage partition, then when I load the file in TIGL viewer ,I get error about the profile but when I put the same profiles as wingairfoil profiles and put all the data as wing, I got the fuselage shape as a wing without any problem,
Thank you for the file, I will try the script, I hope I will succeed to develop into my shape.

Evangelos

**Comment by kngbuzzo** [comment]
Hi Evangelos,
have you by chance forgotten to add a positionings branch? According to the schema, it is mandatory for fuselageType objects, but optional for wingType objects. Apart from that, I really see no difference between the definitions. Adding an empty positionings branch (like so `<positionings/>`) might be sufficient.

Jan

**Comment by vaggos322** [comment]
Hi Jan!

Now that you are mentioning it , I haven't added a positionings branch.
Thanks a lot I will try it.

Evangelos

**Comment by codingpoets** [comment]
Also make sure you have the profiles defined in the right coordinates. You can see in the example that for the fuselage profile I used the y and z coordinates instead of x and z coordinates as commonly used for wing profiles.
If you use the x and z coordinates to define your fuselage profiles make sure that you rotate the profiles by 90 degree around the corresponding z axis.

**Comment by vaggos322** [comment]
Yes it makes sense,I will do that.
