### ISSUE TITLE
uID of componentSegment Element should be required

### ISSUE THREAD

**Issue by rainman110** [DLR-LY/CPACS#494]
Currently, the uID attribute of the componentSegment element is optional.

Is this intentional?

Without any uID, the componentSegment cannot be referenced by other elements.

Therefore, I propose to make the componentSegment uID required.

This could be added to CPACS 3.

**Comment by codingpoets** [comment]
Indeed, the uID should be required. Will be fixed in CPACS 3

**Comment by rainman110** [comment]
Duplication of #450
