### ISSUE TITLE
Add Generic System Components implemented in TiGL

### ISSUE THREAD

**Issue by codingpoets** [DLR-LY/CPACS#496]
In order to model generic system components with simplified shapes, a genericSystems node should be added to the aircraft model systems node.
I would suggest something like the following at /cpacs/vehicles/aircraft/model/systems:

- genericSystems
    - genericSystem (@uID)
        - geometricBaseType (_cone_|_sphere_|_cube_|_cylinder_)
        - transformation (including scaling, rotation, translation)

**Comment by DLR-LY** [comment]
Fixed with 32384bdc2b9162b1e981421b7bca05e899a2c02b
