### ISSUE TITLE
Replace old Link for Issue dokumentation

### ISSUE THREAD

**Issue by AxelBerres** [DLR-LY/CPACS#501]
The old Link http://code.google.com/p/cpacs/issues/list must be replaced with the new Link https://github.com/DLR-LY/CPACS/issues

**Comment by codingpoets** [comment]
Could you concretize were you want the link to be replaced? Do you refer to the release log for releases 2.2.1 and earlier?

**Comment by codingpoets** [comment]
Closed due to inactivity
