### ISSUE TITLE
change coordinate system for aeroPerformanceMap from cpacs CS to aero CS

### ISSUE THREAD

**Issue by codingpoets** [DLR-LY/CPACS#504]
@CLiersch and others proposed to change the coordinate system for the aeroPerformanceMapType to aerodynamic coordinates.

Argument is that is the commonly used CS for aerodynamic data and that it improves interpretability.

Counting against it is the fact that we should avoid using different coordinate systems throughout cpacs. The less coordinate systems we use in cpacs, the less interpretations errors I would expect for the data.

**Comment by sdeinert** [comment]
I also think the aerodynamic coordinate system should be introduced (at least as an optional alternative). This would help when storing the different drag components separately, then the sum of all components would yield the drag value in the aeroPerformanceMap. The storage of aerodynamic results in the aircraft coordinate system would make this much more complicated.

**Comment by codingpoets** [comment]
I think we should avoid options where possible. Whenever there is an option on how to give information tools will only implement one of the options which negates the idea of a central data format. Therefore I am not in favor of an optional alternative.
