### ISSUE TITLE
allow storing multiple performance map per aircraft model

### ISSUE THREAD

**Issue by codingpoets** [DLR-LY/CPACS#507]
In some use cases a collection of different performance maps is required. This would allow to consider effects caused by configurational changes which are not covered through the additional control surfaces.

It would also alow a component wise aeroPerformanceMap or a separation of different drag coefficients into different performance maps.

If we introduce a way to define performance maps in a hierarchy we could use it to store drag breakdowns (e.g. by coefficient or by component). 
But especially for the component wise drag breakdown, the individual maps might not add up to the full one, depending on whether the intreference drag is somewhat considered in the single component maps.

I think as a first step a flat list of aeroPerformanceMaps should be introduced, allowing to manually construct a breakdown. Maybe some kind of grouping could be introduced (using the maps uIDs) where all the individual maps have to add up to another map.

**Comment by DLR-LY** [comment]
Closed by #530
