### ISSUE TITLE
Specify if genericGeometryComponents are added or substracted

### ISSUE THREAD

**Issue by sdeinert** [DLR-LY/CPACS#510]
Could we add an additional attribute to the genericGeometryComponent element that specifies its behaviour for boolean operations?

So if booleanBehaviour=='add', the geometry will be added to the CPACS model (default behaviour).
If booleanBehaviour=='substract', the geometry is substracted allowing to model arbitrarily shaped volumes inside of the CPACS model (e.g. engine inlets inside the fuselage).

The naming of the attribute and its possible values is just a suggestion and to be discussed. But the addition of such a principle would add substantial modelling possibilities with non-parametric geometries.

**Comment by codingpoets** [comment]
Thank you for your proposal. Currently this node is used to add components to the aircraft for which there is no sufficient geometrical definition in CPACS. There is no operation associated with it.
If you want to use it for boolean operation with another shape you might want to specify on which other shape the operation should be performed.
Although in principle it could also be performed on all intersecting shapes.

Could there be cases where this behaviour is not desirable?
Such as the cabin volume should be substracted from the fuselage but the defined wing box should remain although intersecting with both.

**Comment by sdeinert** [comment]
I think this attribute should generally state the "sign" of the geometry, whether it is a positive or negative volume. Whether to apply any boolean operations on that geometry (be it "add" or "substract") should then be decided by the code that is using this definition. Also the question with which CPACS components it should be combined should be decided by the user code.

Maybe one option (if you want to specify that already in CPACS) might be to also add a parentUID entry. This way one could specify one CPACS element on which the genericGeometry should be added/substracted.
This would also alleviate placing these types of geometry relative to CPACS components.

**Comment by ArneBachmann** [comment]
What comes to my mind spontaneously:
Either have a strict order to apply add/subtract shapes, or
use parenthesis-style to group and combine operations hierarchically, and/or
support union, difference, intersection operations instead of add/subtract.

**Comment by sdeinert** [comment]
Is it really necessary to specify the order and combinations used for Boolean operations in CPACS?
This is not done for standard CPACS components such as wings or fuselages either, as these kind of operations also depend on what the user wants to do with the model.

My intention was merely to specify how the genericGeometryComponent behaves in case it is part of a Boolean operation. But this attribute should not state that the genericGeometry _must_ be used for Boolean operations.

This should really only be a property of the genericGeometry.
Specifying order and participants of Boolean operations in CPACS is a step too far from my point of view.

**Comment by DLR-LY** [comment]
As far as I know, boolean operations can only be done on solid geometries. Most shapes in CPACS define surfaces. What if we have open surfaces which cannot be converted into solids directly?

**Comment by codingpoets** [comment]
As discussed with @sdeinert the options will be checked on a prototype and when finished, a new proposal will be made.
The issue is closed for now.
