### ISSUE TITLE
Wing stringer definition

### ISSUE THREAD

**Issue by rmaierl** [DLR-LY/CPACS#511]
We have problems with the wing stringer definition:

It is possible that a stringer definition without pitch or number of stringer is valid with the current schema.
There should be a mandatory choice between _pitch_ and _numberOfStringer_ for the default stringer definition.

It is not possible to define multiple explicit stringer per cell.
Our current solution is that the, explicit stringer is not a choice in the stringer definition.
It is an additional type.

I would suggest _stringerStructureUID_ mandatory and then a choice of six different sequences.
Here the six possible explicit stringer definitions:

>
    <cell>

    ...

    <explicitStringers>

    <explicitStringerSingleInOut>

      <xsiIB1>...</xsiIB1>

      <xsiOB1>...</xsiOB1>

      <stringerStructureUID>...</stringerStructureUID>

    </explicitStringerSingleInOut>

   
  <explicitStringers>

    <explicitStringerSingleInAngle>

      <xsiIB1>...</xsiIB1>

      <stringerStructureUID>...</stringerStructureUID>

      <angle>...</angle>

      <angleReference>...</angleReference>

    </explicitStringerSingleInAngle>

  
  <explicitStringers>

    <explicitStringerSingleOutAngle>

      <xsiOB1>...</xsiOB1>

      <stringerStructureUID>...</stringerStructureUID>

      <angle>...</angle>

      <angleReference>...</angleReference>

    </explicitStringerSingleOutAngle>

  <explicitStringers>

    <explicitStringerSetInOut>

      <xsiIB1>...</xsiIB1>

      <xsiIB2>...</xsiIB2> 

      <xsiOB1>...</xsiOB1>

      <xsiOB2>...</xsiOB2> 

      <numberOfStringer>...</numberOfStringer>

      <stringerStructureUID>...</stringerStructureUID>

    </explicitStringerSetInOut>

  <explicitStringers>

    <explicitStringerSetInAngle>

      <xsiIB1>...</xsiIB1>

      <xsiIB2>...</xsiIB2> 

      <numberOfStringer>...</numberOfStringer>

      <stringerStructureUID>...</stringerStructureUID>

      <angle>...</angle>

      <angleReference>...</angleReference>

    </explicitStringerSetInAngle>

  <explicitStringers>

    <explicitStringerSetOutAngle>

      <xsiOB1>...</xsiOB1>

      <xsiOB2>...</xsiOB2> 

      <numberOfStringer>...</numberOfStringer>

      <stringerStructureUID>...</stringerStructureUID>

      <angle>...</angle>

      <angleReference>...</angleReference>

    </explicitStringerSetOutAngle>

    </explicitStringers>

    </cell>

**Comment by codingpoets** [comment]
I agree that stringerStructureUID should be mandatory.
Please check the implementation in the "explicit-stringers" branch and check if this is what you intended.
Could you provide the descriptions for the parameters and choices marked with "TO BE FILLED"?

**Comment by codingpoets** [comment]
I just realized that your suggestion is not valid XSD. Nodes with the same name cannot appear in different options for the choice element. One possible solution for this is to create separate classes for the different options. but that would add an additional layer of nodes.
That would result in something like the following:

```
<explicitStringer>

  <option6>

    <xsiOB1>...</xsiOB1>

    <xsiOB2>...</xsiOB2> 

    <numberOfStringer>...</numberOfStringer>

    <stringerStructureUID>...</stringerStructureUID>

    <angle>...</angle>

    <angleReference>...</angleReference>

  </option6>

</explicitStringer>
```

Although we should find some more suitable term than "option6".
Do you agree on this approach? Could you provide appropriate terms for the different options?

**Comment by codingpoets** [comment]
I think we should take the _ribsDefinitionType_ as an example and create a class for each option.

**Comment by rmaierl** [comment]
Ok, then I would suggest following naming convention (please adapt if you have a better word)
'Single' - If there is only one stringer
'Set' - If there is more than one stringer
'In' - If the stringer has an inner position
'Out' - If the stringer has an outer position
'Angle' - If the stringer has an angular definition.

I updated my suggestion above

**Comment by codingpoets** [comment]
I have two questions I want to raise.

1. I just realized that there is no pitch option in any of the six definitions. Is that on purpose?
2. This solution seems pretty complicated for something which is, from my point of view, not a serious issue. I bet you will be able to find multiple places in CPACS where we do not rule out all nonsense combinations in the schema entirely. Is it really necessary that we restrict the schema in such a way that only valid combinations of nodes can be used or can't we rather expect the user to give a reasonable set of nodes as long as we explain it in the documentation?

**Comment by codingpoets** [comment]
I pushed a new suggestion which I consider a reasonable compromise. Please take a look at the structure implemented in branch "_explicit-stringers_" to see if you agree.

**Comment by rmaierl** [comment]
The pitch is missing, because this can be realized with with the common stringer definition
The target of the explicit stringer is to be able to connect stringer sets in span-wise direction, this is not possible with the pitch definition.

I think your suggestion is good. It was not clear for me how to define 'use 2 out of 3' in CPACS.
The logical checks can be done in the tools.

**Comment by codingpoets** [comment]
> I think your suggestion is good. It was not clear for me how to define 'use 2 out of 3' in CPACS.
With the current definition one could still use the same option twice, like in:
```
<explicitStringer>
  <xsiInnerBorder />
  <xsiInnerBorder />
</explicitStringer>
```
Which is valid according to the schema but does not make sense. But I think we can leave that to the users to check. There is no simple way to constrain it to exclusive options.
