### ISSUE TITLE
Nodes <name> and <description> should not be mandatory

### ISSUE THREAD

**Issue by rmaierl** [DLR-LY/CPACS#512]
The nodes _name_ and _description_ should be optional in all elements

The node _name_ is e.g. mandatory in the generic geometry components

The node _description_ is e.g. mandatory for _fuel_ and _sparSegments_

**Comment by codingpoets** [comment]
Should names really be optional? I would consider a name to be required to at least get an idea of what a node is there for. For descriptions I agree.

**Comment by codingpoets** [comment]
I am more in favor of making all name nodes mandatory.

**Comment by sdeinert** [comment]
True, but after making all uIDs required, isn't this kind of doubling the work? Since one already needs to define a uID for a component why define a name as well? From my experience I mostly only copy the uID as name.

**Comment by sdeinert** [comment]
That is true. Just a thought.

**Comment by codingpoets** [comment]
Thank you for sharing your thoughts. This is very valuable for the development of CPACS. :)
If you have no further objections I will close this issue with #548. For now I will not make all names mandatory but in my humble opinion we should consider it in future.
