### ISSUE TITLE
doorElement Documentation Error

### ISSUE THREAD

**Issue by marcengelmann** [DLR-LY/CPACS#540]
Hi there, I am currently implementing the CPACS file format in the PAXelerate Boarding Simulation and I discovered a mistake in the documentation. 
In the doorElement documentation it is written that the x is the forward x coordinate of the door relative to the cabin,

Having used an existing CPACS file now I think that the x position is rather linked to the origin of the aircraft than the cabin. Can you confirm this?

**Comment by codingpoets** [comment]
Same position as in #539.
If the current practice differs from the documentation we need to discuss whether we should change it. But for now I don't consider it an error.
